version: '3'

services:
  moodle:
    image: bitnami/moodle:latest
    ports:
      - "80:80"
    environment:
      - MOODLE_USERNAME=user
      - MOODLE_PASSWORD=password
      - MOODLE_EMAIL=user@example.com
    volumes:
      - moodle_data:/bitnami/moodle
    depends_on:
      - mariadb

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  moodle_data:
  mariadb_data:

      
